# Generated by Django 6.0.3 on 2026-05-12 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='botchats',
            name='bot',
            field=models.CharField(),
        ),
    ]
