# Generated by Django 6.0.4 on 2026-05-11 15:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('extractor', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='files',
            old_name='file_name',
            new_name='file',
        ),
    ]
